
NBSP = "\u00A0"

CATEGORY = {
    'SPELL': 'Орфография/грамматика',
    'PUNCT': 'Знаки препинания',
    'TYPO': 'Типографика',
    'WS': 'Пробелы/механика',
    'CAPTION': 'Оформление подписей (ГОСТ)',
    'BRAND': 'Терминология/бренды',
    'GOST34': 'Ссылки на стандарты',
}

SEVERITY_ERROR = "ошибка"
SEVERITY_WARN = "предупреждение"

RID = {
    'SPELL_RU': 'SPELL_RU',
    'SPELL_EN': 'SPELL_EN',
    'PUNCT_SPACE_BEFORE': 'PUNCT_SPACE_BEFORE',
    'PUNCT_NO_SPACE_AFTER': 'PUNCT_NO_SPACE_AFTER',
    'PUNCT_DOUBLE_COMMA': 'PUNCT_DOUBLE_COMMA',
    'PUNCT_DOUBLE_SEMI': 'PUNCT_DOUBLE_SEMI',
    'PUNCT_DOUBLE_COLON': 'PUNCT_DOUBLE_COLON',
    'PUNCT_TWO_DOTS': 'PUNCT_TWO_DOTS',
    'PUNCT_MANY_DOTS': 'PUNCT_MANY_DOTS',
    'PAREN_SPACE_AFTER_OPEN': 'PAREN_SPACE_AFTER_OPEN',
    'PAREN_SPACE_BEFORE_CLOSE': 'PAREN_SPACE_BEFORE_CLOSE',
    'WS_DOUBLE_SPACES': 'WS_DOUBLE_SPACES',
    'WS_TABS': 'WS_TABS',
    'WS_TRAILING': 'WS_TRAILING',
    'WS_NO_SPACE': 'WS_NO_SPACE',
    'ABBR_SPACING': 'ABBR_SPACING',
    'TABLE_NUMBER_SEQUENCE': 'TABLE_NUMBER_SEQUENCE',
    'TABLE_NUMBER_DUPLICATE': 'TABLE_NUMBER_DUPLICATE',
    'TABLE_NO_TITLE': 'TABLE_NO_TITLE',
    'CAPTION_DASH': 'CAPTION_DASH',
    'CAPTION_DASH_SPACING': 'CAPTION_DASH_SPACING',
    'FIG_NUMBER_SEQUENCE': 'FIG_NUMBER_SEQUENCE',
    'FIG_NUMBER_DUPLICATE': 'FIG_NUMBER_DUPLICATE',
    'FIG_NO_TITLE': 'FIG_NO_TITLE',
    'FIG_DASH': 'FIG_DASH',
    'BRAND_POSTGRES_PRO': 'BRAND_POSTGRES_PRO',
    'BRAND_POSTGRESQL': 'BRAND_POSTGRESQL',
    'BRAND_REDIS_SPELL': 'BRAND_REDIS_SPELL',
    'BRAND_REDIS_CASE': 'BRAND_REDIS_CASE',
    'OUTDATED_GOST_34_201_89': 'OUTDATED_GOST_34_201_89',
    'OUTDATED_GOST_34_602_89': 'OUTDATED_GOST_34_602_89',
    'SPACE_HYPHEN_SPACE': 'SPACE_HYPHEN_SPACE',
    'DASH_SPACING': 'DASH_SPACING',
    'HYPHEN_INSTEAD_OF_DASH': 'HYPHEN_INSTEAD_OF_DASH',
}
